module.exports = {
  "ru": {
    "Language": "Язык",
    "Login": "Вход",
    "Email": "Электронная почта",
    "Password": "Пароль",
    "Apply": "Применить",
    "SignIn": "Войти",
    "SignOut": "Выйти",
    "SignUp": "Регистрация",
    "forgotPassword": "Если вы забыли пароль, нажмите меня)",
    "EnterCity": "Введите город",
    "City": "Город",
    "HOME": "ГЛАВНАЯ",
    "HISTORY": "ИСТОРИЯ",
    "PROFILE": "ПРОФИЛЬ",
    "GetWeather": "ПОЛУЧИТЬ ПОГОДУ",
    "CurrentWeather": "Текущая погода",
    "Location": "Местоположение",
    "Temperature": "Температура",
    "FeelsLike": "Ощущается как",
    "Weather": "Погода",
    "WindSpeed": "Скорость ветра",
    "Humidity": "Влажность",
    "Pressure": "Давление",
    "Coordinates": "Координаты",
    "WeatherThreeHours": "Погода за последние 3 часа",
    "ExtendedForecast": "Прогноз на 14 дней",
    "Date": "Дата",
    "MinMax": "Мин/Макс температура",
    "CityInformation": "Информация о городе",
    "Name": "Имя",
    "Latitude": "Широта",
    "Longitude": "Долгота",
    "Country": "Страна",
    "Population": "Население",
    "IsCapital": "Столица",
    "AboutUs": "О нас",
    "WeatherWebSite.": "Сайт погоды.",
    "Ass": "Задание 2 по веб-технологиям (бэк-энд).",
    "Made": "Сделано Ангсаром",
    "DateTime": "Дата: Время",
    "Admin": "Администратор",
    "AdminPanel": "Панель Админа",
    "Username": "Имя пользователя",
    "Status": "Статус",
    "Action": "Действие",
    "Edit" : "Изменить",
    "Delete" : "Удалить",
    "User" : "Пользователь",
    "UpdateUser" : "Обновить данные",
    "Cancel" : "Отменить",
    "Charts" : "ГРАФИКИ",
    "Chart" : "График",
    "AddUser" : "Добавить Пользователя",
    "CreateUser" : "Создать Пользователя",
  },
  "en": {
    "Language": "Language",
    "Login": "Login",
    "Email": "Email",
    "Password": "Password",
    "Apply": "Apply",
    "SignIn": "Sign In",
    "SignOut": "Sign Out",
    "SignUp": "Sign Up",
    "forgotPassword": "If you forgot password, press me)",
    "EnterCity": "Enter City",
    "City": "City",
    "HOME": "HOME",
    "HISTORY": "HISTORY",
    "PROFILE": "PROFILE",
    "GetWeather": "GET WEATHER",
    "CurrentWeather": "Current Weather",
    "Location": "Location",
    "Temperature": "Temperature",
    "FeelsLike": "Feels Like",
    "Weather": "Weather",
    "WindSpeed": "Wind Speed",
    "Humidity": "Humidity",
    "Pressure": "Pressure",
    "Coordinates": "Coordinates",
    "WeatherThreeHours": "Weather for the last 3 hours",
    "ExtendedForecast": "Extended Forecast (14 Days)",
    "Date": "Date",
    "MinMax": "Min/Max Temp",
    "CityInformation": "City Information",
    "Name": "Name",
    "Latitude": "Latitude",
    "Longitude": "Longitude",
    "Country": "Country",
    "Population": "Population",
    "IsCapital": "Is Capital",
    "AboutUs": "About Us",
    "WeatherWebSite.": "Weather WebSite.",
    "Ass": "Assignment2 of WEB Technologies(Back-End).",
    "Made": "Made with by Angsar",
    "DateTime": "Date : Time",
    "Admin": "Admin",
    "AdminPanel": "Admin Panel",
    "Username": "Username",
    "Status": "Status",
    "Action": "Action",
    "Edit" : "Edit",
    "Delete" : "Delete",
    "User" : "User",
    "UpdateUser" : "Update User",
    "Cancel" : "Cancel",
    "Charts" : "CHARTS",
    "Chart" : "Chart",
    "AddUser" : "Add User",
    "CreateUser" : "Create User",
  }
}
